name: Update Fork

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v2
        with:
          repository: paihari/s-and-p-500-companies
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up git for upstream
        run: |
          git remote add upstream https://github.com/datasets/s-and-p-500-companies.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          
      - name: Push changes to fork
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
